version: "3.8"

services:
    postgres:
        image: docker.io/postgres:16-alpine
        container_name: rivet_postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: rivet
            POSTGRES_PASSWORD: rivet
            POSTGRES_DB: rivet
        volumes:
            - postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U rivet"]
            interval: 5s
            timeout: 5s
            retries: 5

    orchestrator:
        image: docker.io/debian:bookworm-slim
        container_name: rivet_orchestrator
        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - "8080:8080"
        environment:
            RUST_LOG: debug
            DATABASE_URL: postgres://rivet:rivet@postgres:5432/rivet
            ORCHESTRATOR_BIND_ADDR: 0.0.0.0:8080
        volumes:
            # Mount debug binaries from the project to run the orchestrator binary directly
            - ./target/debug:/app/target/debug:ro
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "curl -f http://localhost:8080/api/health || exit 1",
                ]
            interval: 5s
            timeout: 3s
            retries: 10
            start_period: 10s
        command:
            - sh
            - -c
            - |
                set -eu; \
                # Ensure minimal runtime deps exist (installs only on start; ok for local dev).
                apt-get update && apt-get install -y --no-install-recommends ca-certificates libssl3 curl; \
                exec /app/target/debug/rivet-orchestrator

    runner:
        image: docker.io/debian:bookworm-slim
        container_name: rivet_runner
        depends_on:
            orchestrator:
                condition: service_healthy
        environment:
            RUST_LOG: debug
            ORCHESTRATOR_URL: http://orchestrator:8080
            RUNNER_ID: runner-1
        volumes:
            # Mount debug binaries from the project to run the runner binary directly
            - ./target/debug:/app/target/debug:ro
        command:
            - sh
            - -c
            - |
                set -eu; \
                apt-get update && apt-get install -y --no-install-recommends ca-certificates libssl3; \
                exec /app/target/debug/rivet-runner

volumes:
    postgres-data:
